apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "k8s-snapshots.fullname" . }}
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
{{ include "k8s-snapshots.release_labels" . | indent 4 }}
data:
  kube_entry: |
{{ .Files.Get "docker/kube_entry" | indent 4 }}
